stages:
  - triggers

workflow:
  rules:
    # If `$FORCE_GITLAB_CI` is set, create a pipeline.
    - if: '$FORCE_GITLAB_CI'
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'
    # If commit title starts with 'run-ci:'
    - if: '$CI_COMMIT_TITLE =~ /^(r|R)un-ci:/'

trigger_llvm12:
  stage: triggers
  trigger:
    include: .gitlab-pipelines/llvm12/config.yml
    strategy: depend

